added jwt, moved logic to auth resolver
TheRealJackiBoi/FullStackExam-Backend pull request #14
Opened 2024-03-07 13:13 UTC by HeinLarsen

2024-03-08 14:45 UTC, JackOulund requested changes

2024-03-08 14:45 UTC, JackOulund commented on src/models/auth.ts
> +const userSchema = new mongoose.Schema<IAuth>(
Maybe not called user... Redundant name

2024-03-08 14:45 UTC, JackOulund commented on src/resolvers/query.ts
> +  return jwt.sign({ id: user._id! }, process.env.JWT_SECRET!, {
add role to token

2024-03-08 14:45 UTC, TheRealJackiBoi commented on src/schema.ts
> +    user: User!
add email key

2024-03-12 10:48 UTC, Juliuslassen approved these changes

2024-03-12 10:50 UTC, merged